[build]
    functions = "api/"
    command = '#'

[[redirects]]
  from = "/index.html"
  to = "/.netlify/functions/get-paste"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/"
  to = "/.netlify/functions/get-paste"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/new.html"
  to = "/new"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
